# Welcome to Jekyll!

title: Sweet Peonies
email:
description: Simple ideas for everyday living
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.sweetpeonies.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

gems:
  - jekyll-archives
  - jekyll-paginate

exclude:
  - node_modules
  - Gemfile*
  - package.json

collections:
  posts:
    permalink: /blog/:year/:month/:day/:title

jekyll-archives:
  enabled:
    - year
    - month
    - category
  layout: 'default'
  permalinks:
    year: '/blog/:year/'
    month: '/blog/:year/:month/'
    tag: '/tag/:name/'
    category: '/category/:name/'

paginate: 5
paginate_path: "/blog/page/:num"
